config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, :scope => [:list]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, :through => :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @movie = Movie.find(params[:bookmark][:movie_id])
    @list = List.find(params[:list_id])
    @bookmark.movie = @movie
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "Submit bookmark"%>
<% end %>

app/views/bookmarks/new.html.erb
<h1>Create a ew bookmark</h1>

<%= render "form", bookmark: @bookmark %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <%= link_to root_path do %>
     <%= image_tag "tickets.png", class: "homeicon" %>
    <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <%= link_to "My lists", lists_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "New list", new_list_path, class:"nav-link" %>
            </li>
          </ul>
        </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name, placeholder: "My new list" %>
  <%= f.submit class:"button form" %>
<% end %>

app/views/lists/index.html.erb
<div class="banner-lists" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1524779709304-40b5a3560c60?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8Y29sbGVjdGlvbnxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60);">
  <div class="container text-center">
    <h1>All your lists</h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>
  </div>
</div>

<div class="container add">
<%= link_to "Add a list", new_list_path, class:"add-lists" %>
</div>

<div class="cards container">
  <% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://picsum.photos/200/300)">
        <div>
          <h2> <%= list.name %></h2>
        </div>
      </div>
      <% end %>
    <% end %>
</div>

app/views/lists/new.html.erb
<div class="container new">
<h1 class="createlist">Create a new list</h1>
<%= render "form", list: @list %>
</div>

app/views/lists/show.html.erb
<div class="banner show" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1505775561242-727b7fba20f0?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGZpbG18ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60);">
    <h1><%= @list.name %></h1>
  <div class="container my-3 links">
    <%= link_to "All your lists", lists_path, class:"button-back" %>
    <%= link_to "Delete #{@list.name}",
                list_path(@list),
                method: :delete,
                data: { confirm: "Are you sure?" },
                class:"button-delete" %>
    <%= link_to "Add a movie", new_list_bookmark_path(@list), class:"button-add" %>
  </div>
</div>


<div class="cards container">
  <% @list.bookmarks.each do |bookmark| %>
      <div class="card-category-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url( <%= bookmark.movie.poster_url %> )">
        <div class="infos">
          <h2> <%= bookmark.movie.title %> </h2>
          <p> <%= bookmark.comment %> </p>
          <%= link_to ('<i class="far fa-trash-alt"></i>').html_safe, bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure you want to remove #{bookmark.movie.title} from your #{@list.name} list"}, id:"delete-movie" %>
        </div>
      </div>
    <% end %>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/4722571/pexels-photo-4722571.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500);">
  <div class="container">
    <h1>Save your movies</h1>
    <%= link_to "Start Now", lists_path, class:"button" %>
  </div>
</div>